//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechatronicsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniUsersAuthenticate
    {
        public AlumniUsersAuthenticate()
        {
            this.EmployeeInformations = new HashSet<EmployeeInformation>();
            this.PersonalInformations = new HashSet<PersonalInformation>();
            this.EducationalInformations = new HashSet<EducationalInformation>();
            this.ProfessionalDetails = new HashSet<ProfessionalDetail>();
        }
    
        public int alumni_id { get; set; }
        public Nullable<int> alumni_username { get; set; }
        public string almuni_password { get; set; }
        public string alumni_name { get; set; }
        public string alumni_survey_status { get; set; }
        public string alumni_employee_survey_status { get; set; }
        public string alumni_email { get; set; }
        public string alumni_firsttime_loggedin { get; set; }
    
        public virtual ICollection<EmployeeInformation> EmployeeInformations { get; set; }
        public virtual ICollection<PersonalInformation> PersonalInformations { get; set; }
        public virtual ICollection<EducationalInformation> EducationalInformations { get; set; }
        public virtual ICollection<ProfessionalDetail> ProfessionalDetails { get; set; }
    }
}
