//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechatronicsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalInformation
    {
        public int Id { get; set; }
        public string latest_qualification { get; set; }
        public string degree_title { get; set; }
        public string institute { get; set; }
        public string year_of_completion { get; set; }
        public string majors { get; set; }
        public string alumni_id { get; set; }
    
        public virtual AlumniUsersAuthenticate AlumniUsersAuthenticate { get; set; }
    }
}
