//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechatronicsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInformation
    {
        public string full_name { get; set; }
        public string department { get; set; }
        public int reg_number { get; set; }
        public string email { get; set; }
        public string contact_number { get; set; }
        public string pec_registration { get; set; }
        public int id { get; set; }
        public string alumni_id { get; set; }
    
        public virtual AlumniUsersAuthenticate AlumniUsersAuthenticate { get; set; }
    }
}
