//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechatronicsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalDetail
    {
        public int Id { get; set; }
        public int alumni_id { get; set; }
        public string job_title { get; set; }
        public string company_name { get; set; }
        public string department { get; set; }
        public string work_location { get; set; }
        public string work_contact { get; set; }
        public string email { get; set; }
        public string start_date { get; set; }
        public string supervisor_name { get; set; }
        public string supervisor_email { get; set; }
        public string supervisor_contact { get; set; }
    
        public virtual AlumniUsersAuthenticate AlumniUsersAuthenticate { get; set; }
    }
}
